## -*- docker-image-name: "martinralbrecht/fplll" -*-

FROM debian
MAINTAINER Martin Albrecht <martin.albrecht@royalholloway.ac.uk>

ARG BRANCH=master

RUN apt update && \
    apt install -y build-essential libtool git autoconf libgmp-dev libmpfr-dev libqd-dev && \
    apt clean && \
    git clone --branch $BRANCH https://github.com/fplll/fplll && \
    cd fplll && \
    autoreconf -i && \
    ./configure && \
    make install
    
